-- Semilla de categorías (editable por el admin)
insert into categories (group_slug, slug, name, icon, color, animation_key, sort, is_system) values
  ('ritmo','express','Express (≤15 min)','zap','#F6E3C8','fast',1,true),
  ('ritmo','rapidas','Rápidas (≤30 min)','zap','#F6E3C8','fast',2,true),
  ('ritmo','con-calma','Con calma','zap','#F6E3C8','fast',3,true),
  ('ritmo','coccion-lenta','Cocción lenta','zap','#F6E3C8','fast',4,true),
  ('ritmo','fin-de-semana','De fin de semana','zap','#F6E3C8','fast',5,true),
  ('ritmo','con-anticipacion','Se prepara con anticipación','zap','#F6E3C8','fast',6,true),
  ('formalidad','formales','Formales','wine','#E9DCC3','gala',7,true),
  ('formalidad','de-gala','De gala','wine','#E9DCC3','gala',8,true),
  ('formalidad','informales','Informales','wine','#E9DCC3','gala',9,true),
  ('formalidad','del-diario','Del diario','wine','#E9DCC3','gala',10,true),
  ('formalidad','impresionar','Para impresionar','wine','#E9DCC3','gala',11,true),
  ('formalidad','compartir','Para compartir','wine','#E9DCC3','gala',12,true),
  ('momento','desayuno','Desayuno','sunrise','#F4DDD2','sun',13,true),
  ('momento','brunch','Brunch','sunrise','#F4DDD2','sun',14,true),
  ('momento','almuerzo','Almuerzo','sunrise','#F4DDD2','sun',15,true),
  ('momento','merienda','Merienda','sunrise','#F4DDD2','sun',16,true),
  ('momento','cena','Cena','sunrise','#F4DDD2','sun',17,true),
  ('momento','madrugada','Antojo de madrugada','sunrise','#F4DDD2','sun',18,true),
  ('plato','entradas','Entradas','utensils','#EFD5D0','soft',19,true),
  ('plato','sopas','Sopas y cremas','utensils','#EFD5D0','soft',20,true),
  ('plato','ensaladas','Ensaladas','utensils','#EFD5D0','soft',21,true),
  ('plato','carnes','Carnes','utensils','#EFD5D0','soft',22,true),
  ('plato','aves','Aves','utensils','#EFD5D0','soft',23,true),
  ('plato','pescados','Pescados y mariscos','utensils','#EFD5D0','soft',24,true),
  ('plato','pastas-arroces','Pastas y arroces','utensils','#EFD5D0','soft',25,true),
  ('plato','guarniciones','Guarniciones','utensils','#EFD5D0','soft',26,true),
  ('plato','salsas','Salsas y aderezos','utensils','#EFD5D0','soft',27,true),
  ('plato','panes','Panes y masas','utensils','#EFD5D0','soft',28,true),
  ('plato','postres','Postres','utensils','#EFD5D0','soft',29,true),
  ('plato','reposteria','Repostería','utensils','#EFD5D0','soft',30,true),
  ('plato','bebidas','Bebidas y cócteles','utensils','#EFD5D0','soft',31,true),
  ('plato','conservas','Conservas','utensils','#EFD5D0','soft',32,true),
  ('ocasion','navidad','Navidad','party-popper','#E3D6EA','twinkle',33,true),
  ('ocasion','ano-nuevo','Año Nuevo','party-popper','#E3D6EA','twinkle',34,true),
  ('ocasion','cumpleanos','Cumpleaños','party-popper','#E3D6EA','twinkle',35,true),
  ('ocasion','bodas','Bodas y aniversarios','party-popper','#E3D6EA','twinkle',36,true),
  ('ocasion','reuniones','Reuniones','party-popper','#E3D6EA','twinkle',37,true),
  ('ocasion','dia-padres','Día de la madre/padre','party-popper','#E3D6EA','twinkle',38,true),
  ('ocasion','semana-santa','Semana Santa','party-popper','#E3D6EA','twinkle',39,true),
  ('ocasion','parrilladas','Parrilladas','party-popper','#E3D6EA','twinkle',40,true),
  ('ocasion','picnic','Picnic','party-popper','#E3D6EA','twinkle',41,true),
  ('dieta','vegetarianas','Vegetarianas','leaf','#CBD9C8','sprout',42,true),
  ('dieta','veganas','Veganas','leaf','#CBD9C8','sprout',43,true),
  ('dieta','sin-gluten','Sin gluten','leaf','#CBD9C8','sprout',44,true),
  ('dieta','sin-lacteos','Sin lácteos','leaf','#CBD9C8','sprout',45,true),
  ('dieta','ligeras','Ligeras','leaf','#CBD9C8','sprout',46,true),
  ('dieta','proteina','Altas en proteína','leaf','#CBD9C8','sprout',47,true),
  ('dieta','ninos','Para niños','leaf','#CBD9C8','sprout',48,true),
  ('dificultad','principiante','Principiante','chef-hat','#D6E2EA','soft',49,true),
  ('dificultad','intermedio','Intermedio','chef-hat','#D6E2EA','soft',50,true),
  ('dificultad','de-chef','De chef','chef-hat','#D6E2EA','soft',51,true),
  ('origen','herencia','Herencia familiar','book-heart','#EBDDCB','soft',52,true),
  ('origen','mundo','Cocina del mundo','book-heart','#EBDDCB','soft',53,true),
  ('origen','creacion','Creación propia','book-heart','#EBDDCB','soft',54,true),
  ('tecnica','horno','Horno','flame','#F1D9CB','sizzle',55,true),
  ('tecnica','parrilla','Parrilla','flame','#F1D9CB','sizzle',56,true),
  ('tecnica','sarten','Sartén','flame','#F1D9CB','sizzle',57,true),
  ('tecnica','olla-lenta','Olla lenta','flame','#F1D9CB','sizzle',58,true),
  ('tecnica','vapor','Al vapor','flame','#F1D9CB','sizzle',59,true),
  ('tecnica','sin-coccion','Sin cocción','flame','#F1D9CB','sizzle',60,true),
  ('tecnica','fermentacion','Fermentación','flame','#F1D9CB','sizzle',61,true),
  ('tecnica','fritura','Fritura','flame','#F1D9CB','sizzle',62,true),
  ('temporada','primavera','Primavera','sun','#DDE7D5','soft',63,true),
  ('temporada','verano','Verano','sun','#DDE7D5','soft',64,true),
  ('temporada','otono','Otoño','sun','#DDE7D5','soft',65,true),
  ('temporada','invierno','Invierno','sun','#DDE7D5','soft',66,true)
on conflict (slug) do nothing;
